name: Build Github Pages site
on:
 push:
   branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Copy PCB project content to publishing directory
      shell: bash
      run: |
        tools/make-publish-dir pages_dir
    - name: Generate Directory Listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        folder: pages_dir
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages_dir
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
